[package]
name = "silver"
version = "1.1.0"
authors = ["reujab <reujab@gmail.com>"]

description = "A cross-shell customizable powerline-like prompt with icons"
repository = "https://github.com/reujab/silver"
readme = "readme.md"
keywords = ["shell", "prompt", "powerline", "agnoster", "icons"]
categories = ["command-line-utilities"]
license = "Unlicense"

[dependencies]
chrono = "0.4"
clap = {version = "2", features = ["yaml"]}
dirs = "2"
git2 = "0.11"
hostname = "0.1"
humantime = "1"
lazy_static = "1"
libc = "0.2"
regex = "1"
rust-ini = "0.13"
url = "2"

[target.'cfg(not(windows))'.dependencies]
users = "0.9"

[target.'cfg(windows)'.dependencies.winapi]
version = "0.3"
features = [
    "handleapi",
    "processthreadsapi",
    "securitybaseapi"
]
